#ifndef __DRIVERS_VIDEO_VGA_REGS_H__
#define __DRIVERS_VIDEO_VGA_REGS_H__

/* Graphics controller */
#define VGA_GFX_ADDR 0x3ce
#define VGA_GFX_DATA 0x3cf

#define VGA_GFX_SET_RESET 0x00
#define VGA_GFX_EN_SET_RESET 0x01
#define VGA_GFX_COLOR_CMP 0x02
#define VGA_GFX_DATA_ROTATE 0x03
#define VGA_GFX_READ_MAP_SEL 0x04
#define VGA_GFX_MODE 0x05
#define VGA_GFX_MISC 0x06
#define VGA_GFX_CDC 0x07 // color don't care
#define VGA_GFX_BIT_MASK 0x08

/* Sequencer */
#define VGA_SEQ_ADDR 0x3c4
#define VGA_SEQ_DATA 0x3c5

#define VGA_SEQ_RESET 0x00
#define VGA_SEQ_CLOCKING 0x01
#define VGA_SEQ_MAP_MASK 0x02
#define VGA_SEQ_CHAR_MAP_SEL 0x03
#define VGA_SEQ_MEM_MODE 0x04

/* Misc */
#define VGA_MISC_WRITE 0x3c2
#define VGA_MISC_READ 0x3cc

/* Cathode Ray Tube Controller */
#define VGA_CRTC_ADDR 0x3d4
#define VGA_CRTC_DATA 0x3d5

#define VGA_CRTC_HORIZONTAL_TOTAL 0x00
#define VGA_CRTC_HORIZONTAL_DISPLAY_END 0x01
#define VGA_CRTC_HORIZONTAL_BLANK_START 0x02
#define VGA_CRTC_HORIZONTAL_BLANK_END 0x03
#define VGA_CRTC_HORIZONTAL_RETRACE_START 0x04
#define VGA_CRTC_HORIZONTAL_RETRACE_END 0x05
#define VGA_CRTC_VERTICAL_TOTAL 0x06
#define VGA_CRTC_OVERFLOW 0x07
#define VGA_CRTC_PRESET_ROW_SCAN 0x08
#define VGA_CRTC_MAXIMUM_SCAN_LINE 0x09
#define VGA_CRTC_CURSOR_START 0x0a
#define VGA_CRTC_CURSOR_END 0x0b
#define VGA_CRTC_START_ADDR_HI 0x0c
#define VGA_CRTC_START_ADDR_LO 0x0d
#define VGA_CRTC_CURSOR_LOC_HI 0x0e
#define VGA_CRTC_CURSOR_LOC_LO 0x0f
#define VGA_CRTC_VERTICAL_RETRACE_START 0x10
#define VGA_CRTC_VERTICAL_RETRACE_END 0x11
#define VGA_CRTC_VERTICAL_DISPLAY_END 0x12
#define VGA_CRTC_OFFSET 0x13
#define VGA_CRTC_UNDERLINE_LOCATION 0x14
#define VGA_CRTC_VERTICAL_BLANKING_START 0x15
#define VGA_CRTC_VERTICAL_BLANKING_END 0x16
#define VGA_CRTC_MODE_CONTROL 0x17
#define VGA_CRTC_LINE_COMPARE 0x18

/* Attribute Controller */
#define VGA_AC_ADDR 0x3c0
#define VGA_AC_WRITE 0x3c0
#define VGA_AC_READ 0x3c1

#define VGA_AC_MODE_CONTROL 0x10
#define VGA_AC_OVERSCAN_COLOR 0x11
#define VGA_AC_COLOR_PLANE_ENABLE 0x12
#define VGA_AC_HORIZONTAL_PIXEL_PAN 0x13
#define VGA_AC_COLOR_SELECT 0x14

/* DAC */
#define VGA_DAC_ADDR_READ 0x3c7
#define VGA_DAC_ADDR_WRITE 0x3c8
#define VGA_DAC_DATA 0x3c9

#endif
